// Automatically generated by scripts/deploy.js
window.ENV = {
  VITE_UGC_TOKEN_ADDRESS: "0x1eDa37f016bDA3013de7A49e0fb4348c574C1BEf",
  VITE_DONATION_CONTRACT_ADDRESS: "0x11269B64621C93B73d1abb898FE956f6502E13bc",
  VITE_TARGET_CHAIN_ID: "84532",
  VITE_UGF_API_KEY: "ugf_test_your_key_here",
  VITE_UGF_ENDPOINT: "https://testnet.api.ugf.network",
  VITE_UGC_FAUCET_URL: "https://faucet.ugf.network",
  VITE_BACKEND_URL: "http://localhost:4000",
  VITE_WS_URL: "ws://localhost:4000/ws"
};
