import fs from "fs";
import { ethers } from "ethers";
import "dotenv/config";

/**
 * deploy.js — Deploys MockUSD + DonationVault to Base Sepolia.
 *
 * Usage:
 *   1. npx hardhat compile
 *   2. node scripts/deploy.js
 *
 * Requires .env:
 *   PRIVATE_KEY=0x...
 *   BASE_SEPOLIA_RPC_URL=https://sepolia.base.org
 */
async function main() {
  const privateKey = process.env.PRIVATE_KEY;
  if (!privateKey) throw new Error("Set PRIVATE_KEY in .env");

  const rpcUrl = process.env.BASE_SEPOLIA_RPC_URL || "https://sepolia.base.org";
  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const deployer = new ethers.Wallet(privateKey, provider);

  const balance = await provider.getBalance(deployer.address);
  console.log(`\n📦  Deployer: ${deployer.address}`);
  console.log(`💰  Balance:  ${ethers.formatEther(balance)} ETH\n`);

  // ── 1. Use Official UGF TYI_MOCK_USD ────────────────────────────────────────
  const mockUsdAddr = "0x1eDa37f016bDA3013de7A49e0fb4348c574C1BEf";
  console.log(`✅  Using official TYI_MOCK_USD: ${mockUsdAddr}`);

  // ── 2. Deploy DonationVault ────────────────────────────────────────────────
  console.log("🔨  Deploying DonationVault...");
  const vaultArtifact = JSON.parse(
    fs.readFileSync("./contracts/artifacts/contracts/DonationVault.sol/DonationVault.json", "utf8")
  );
  const Vault = new ethers.ContractFactory(vaultArtifact.abi, vaultArtifact.bytecode, deployer);
  const vault = await Vault.deploy();
  await vault.waitForDeployment();
  const vaultAddr = await vault.getAddress();
  console.log(`✅  DonationVault deployed: ${vaultAddr}`);

  // Set the donation token address in the vault
  console.log("⚙️  Setting donation token in vault...");
  const setTokenTx = await vault.setDonationToken(mockUsdAddr);
  await setTokenTx.wait();
  console.log("✅  Donation token configured in vault!");

  // ── 3. Register default causes ─────────────────────────────────────────────
  console.log("\n📋  Registering causes...");
  const causes = [
    { wallet: "0x71C7656EC7ab88b098defB751B7401B5f6d8976F", name: "Plant Trees" },
    { wallet: "0x2546BcD3c84621e976D8185a91A922aE77ECEc30", name: "Clean Water" },
    { wallet: "0xbDA5747bFD65F08deb54cb465eB87D40e51B197E", name: "Education Fund" },
  ];

  const vaultContract = new ethers.Contract(vaultAddr, vaultArtifact.abi, deployer);
  for (const c of causes) {
    const tx = await vaultContract.addCause(c.wallet, c.name);
    await tx.wait();
    console.log(`   ✅  ${c.name} → ${c.wallet}`);
  }

  // ── 4. Output .env values & write env.js ───────────────────────────────────
  console.log("\n══════════════════════════════════════════════");
  console.log("  DEPLOYMENT COMPLETE — Copy to .env:");
  console.log("══════════════════════════════════════════════");
  console.log(`VITE_UGC_TOKEN_ADDRESS=${mockUsdAddr}`);
  console.log(`VITE_DONATION_CONTRACT_ADDRESS=${vaultAddr}`);
  console.log(`VITE_TARGET_CHAIN_ID=84532`);
  console.log("══════════════════════════════════════════════\n");

  const envJsContent = `// Automatically generated by scripts/deploy.js
window.ENV = {
  VITE_UGC_TOKEN_ADDRESS: "${mockUsdAddr}",
  VITE_DONATION_CONTRACT_ADDRESS: "${vaultAddr}",
  VITE_TARGET_CHAIN_ID: "84532",
  VITE_UGF_API_KEY: "ugf_test_optional_legacy",
  VITE_UGF_ENDPOINT: "https://gateway.universalgasframework.com",
  VITE_UGC_FAUCET_URL: "https://universalgasframework.com/faucets",
  VITE_BACKEND_URL: "http://localhost:4000",
  VITE_WS_URL: "ws://localhost:4000/ws"
};
`;
  fs.writeFileSync("./env.js", envJsContent, "utf8");
  console.log("💾  Successfully wrote env.js for the frontend!");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
